apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: linda
resources:
  - service.yaml
  - deployment.yaml

commonLabels:
  app.kubernetes.io/name: linda-notes
  app.kubernetes.io/instance: linda-notes
  app.kubernetes.io/version: "latest"
  app.kubernetes.io/managed-by: GA
  app.kubernetes.io/component: operator
  app.kubernetes.io/part-of: linda-notes
  fintlabs.no/team: flais
  fintlabs.no/org-id: flais.io